---
abstract: 'Provide the static, dynamic libraries and CLI (non-Windows) of the edlib aligner'
author:
  - 'Christos Argyropoulos <chrisarg@gmail.com>'
build_requires:
  Alien::Build: '0.32'
  Alien::Build::MM: '0.32'
  ExtUtils::MakeMaker: '6.52'
  File::Spec: '0'
  Test2::V0: '0'
  Test::Alien: '0'
  Test::Alien::Diag: '0'
  Test::More: '0'
configure_requires:
  Alien::Build: '1.40'
  Alien::Build::MM: '0.32'
  Alien::Build::Plugin::Build::CMake: '0.99'
  ExtUtils::MakeMaker: '6.52'
dynamic_config: 1
generated_by: 'Dist::Zilla version 6.030, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Alien-SeqAlignment-edlib
no_index:
  directory:
    - eg
    - examples
    - inc
    - share
    - t
    - xt
provides:
  Alien::SeqAlignment::edlib:
    file: lib/Alien/SeqAlignment/edlib.pm
    version: '0.04'
requires:
  Alien::Base: '0'
  parent: '0'
  strict: '0'
  warnings: '0'
version: '0.04'
x_alienfile:
  generated_by: 'Dist::Zilla::Plugin::AlienBuild version 0.32'
  requires:
    share:
      Alien::Build::Plugin::Gather::IsolateDynamic: '0.48'
      Alien::cmake3: '0.02'
      Config: '0'
      HTTP::Tiny: '0.044'
      IO::Socket::SSL: '1.56'
      Mozilla::CA: '0'
      Net::SSLeay: '1.49'
      URI: '0'
    system: {}
x_generated_by_perl: v5.38.0
x_serialization_backend: 'YAML::Tiny version 1.74'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
